### ISSUE TITLE
(Can be my local env) but documenting the issue

### ISSUE THREAD

**Issue by emilse-webdev** [WebDevStudios/nextjs-wordpress-starter#1019]
When I try to add pages or posts, after everything has been installed, I can add them but the blocks in gutenberg will give an error of react dom, validateThemeColors is not a function inside blocks.js.

![image](https://user-images.githubusercontent.com/104102110/171510592-ffa3791e-07e2-41cf-9af5-97d2e5dadbb7.png)
![image](https://user-images.githubusercontent.com/104102110/171510658-5b13040f-7f36-4aa4-a902-ed2d85519e7e.png)

**Describe the bug**
validateThemeColors is not a function react-dom.js called from blocks.js

**To Reproduce**

0. Open a wordpress site root directory
1. Clone the repo backend folder in wp-content/
2. Composer install
3. Move theme to themes folder
4. Back to package.json folder, npm install --legacy-peer-deps && npm run dev
5. Configure Algolia, Keys, Settings and open wp-admin/ create a page or post

**Expected behavior**
The usual,

**Additional Info**
I still have to test if installing the plugins in a wordpress clean installation won't remove the issue, because I think it's related to adding next js starter to an existent wordpress site.

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by fiechtor** [comment]
Can confirm, Wordpress > 6.0 does not contain `wp.blockEditor.validateThemeColors` nor `wp.blockEditor.validateThemeGradients`, works fine in 5.9.3 though. Also works by removing the imports and making `defaultColors` and `defaultGradients` variables empty arrays.

Bug is contained in https://github.com/WebDevStudios/wds-headless-blocks plugin.

**Comment by kaelansmith** [comment]
I just created a [duplicate issue ](https://github.com/WebDevStudios/nextjs-wordpress-starter/issues/1049) and then happened to see this right after. If this has been a critical issue since June 1st, I think it's safe to say this project has been abandoned?
